version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: planet_db
    env_file:
      - ./.env
    volumes:
      - planet_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: planet_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: planet_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build: .
    container_name: planet_celery
    command: celery -A planet_core worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  adminer:
    image: adminer
    container_name: planet_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  planet_data:
